### ISSUE TITLE
Unhandled 'error': connect ECONNREFUSED 127.0.0.1:9051

### ISSUE THREAD

**Issue by vyatsun** [atd-schubert/node-tor-control#3]
I'd like to have a way to gracefully handle an ECONNREFUSED error, when Tor is not running. 

The following snippet works fine when Tor is lisneting on port 9051, but when it is not, Node.js exist with code (1), thus killing the app. 

```
var TorControl = require('tor-control');
var control = new TorControl({});
control.signalNewnym(function (err, status) { 
        if (err) {
            console.log(err);
        }
        console.log(status);
});
```
Is there a way I can continue the script execution if Tor is not running?

**Comment by atd-schubert** [comment]
I have to take a look at it...

**Comment by atd-schubert** [comment]
I have already made a new release as version 0.0.2. @vyatsun you can use this one now...
